name: ktb

on:
  push:
    tags:
      - 'v*' # 当你推送 v1.0.0 这样的标签时自动触发
  workflow_dispatch: # 允许手动在网页上点击按钮触发

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      
      - name: Install Dependencies
        run: |
          cd ktb  # 确保这里是你的主项目目录
          flutter pub get
      
      - name: Build Release
        run: |
          cd ktb
          flutter build windows --release
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ktb
          path: ktb/build/windows/runner/Release/
          
      # 可选：自动创建 GitHub Release 并上传
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ktb/build/windows/runner/Release/**
